apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
  token-secret: {{ .Values.env.TOKEN_SECRET | default "REPLACE_WITH_SECRETS_MANAGER_TOKEN" | quote }}
  postgres-uri: {{ .Values.env.POSTGRES_URI | default "postgres://postgres:REPLACE_WITH_SECRETS_MANAGER_PASSWORD@mujcode-postgres:5432/mujcode_db" | quote }}
  redis-uri: {{ .Values.env.REDIS_URI | default "redis://mujcode-redis:6379" | quote }}
  mongodb-uri: {{ .Values.env.MONGODB_URI | default "" | quote }}
